version: "3"

services:
  express-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
      - react-app
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      PORT: 5000
      SECRET_KEY: "KtnZMmr)V}#s&&%eGvfF-#shk8'dC-s~eLwG{;stljNL>L(Z'Oejd.,S(KRw&)"
      MAIL_SEND: "igorslepchenko.cc@gmail.com"
      PASS_SEND: "hxdb ktge hbuy acoq"

  db:
    container_name: postgres_db
    image: postgres:alpine3.17
    ports:
      - "5432:5432"
    volumes:
      - db:/data/db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootroot
      POSTGRES_DB: learn_track

  react-app:
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - "80:80"

volumes:
  db:
