version: '3'
services:
  express-app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:rootroot@db:5432/learn_track?schema=public"
    volumes:
      - .:/app

  db:
    image: postgres:14-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: learn_track
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootroot
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
